server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:          - Path=/users/**
          - Method=GET, POST
        filters:          - RemoveRequestHeader=Coockie

      - id: account-status-check
        uri: lb://account-management-service
        predicates:
          - Path=/account/**
          - Method=GET, POST, PUT, DELETE
        filters:
          - RemoveRequestHeader=Coockie

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
      
