server:
  port: ${PORT:0}
  
spring:
  application:
    name: account-management-service
  devtools:
    restart:
      enabled: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
      
