server:
  port: 0
  
spring:
  application:
    name: account-management-service
  devtools:
    restart:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
      
