server:
  port: ${PORT:0}
  
spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/user-microservice?createDatabaseIfNotExist=true
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
      
token:
  expiration_time: 864000000 # 10 days
  secret: hgfhjfhyutyru676gfcstwr5;
  
login:
  url:
    path: /users/login
    
ip:
  address: host.docker.internal # 127.0.0.1
    
albums:
  url: http://ALBUMS-WS/users/%s/albums
