server:
  port: ${PORT:0}
  
spring:
  application:
    name: user-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/user-microservice?createDatabaseIfNotExist=true
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
